version: "2"
plugins:
  brakeman:
    enabled: true
  eslint:
    enabled: false
  rubocop:
    enabled: true
exclude_patterns:
- "config/"
- "db/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "**/vendor/"
- "**/*.d.ts"